AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless - org.ubf::msite
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  MSiteLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/ubf-msite-api
      RetentionInDays: 1

  MSiteFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ubf-msite-api
      Handler: app.lambda_handler
      Runtime: python3.9
      CodeUri: functions/msite
      MemorySize: 512
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/ubf-msite-role
      Timeout: 15
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

  MSiteMemberTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ubf-msite-members
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: memberId
          AttributeType: S
        -
          AttributeName: fellowshipId
          AttributeType: S
      KeySchema:
        -
          AttributeName: memberId
          KeyType: HASH
      GlobalSecondaryIndexes:
        -
          IndexName: Fellowship-Index
          KeySchema:
            -
              AttributeName: fellowshipId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  MSiteFellowshipTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: fellowshipId
        Type: String
      TableName: ubf-msite-fellowship

  MSiteCampusTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: campusId
        Type: String
      TableName: ubf-msite-campus

  MSiteChapterTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: chapterId
        Type: String
      TableName: ubf-msite-chapter

  MSiteWorshipServiceTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: wsId
        Type: String
      TableName: ubf-msite-ws

  MSiteBibleStudyTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: bStudyId
        Type: String
      TableName: ubf-msite-bible-study

Outputs:
  MSiteApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'
    Export:
      Name: MSiteApi
